'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { api, type Product, type Order } from '@/lib/api'

export default function AdminPage() {
  const router = useRouter()
  const [products, setProducts] = useState<Product[]>([])
  const [orders, setOrders] = useState<Order[]>([])
  const [loading, setLoading] = useState(true)
  const [message, setMessage] = useState('')
  useEffect(() => { const supabase = createClient(); supabase.auth.getUser().then(async ({ data }) => { if (!data.user) return router.replace('/admin/login'); const token = (await supabase.auth.getSession()).data.session?.access_token; try { const [p, o] = await Promise.all([api.adminProducts(token), api.adminOrders(token)]); setProducts(p); setOrders(o) } catch (e) { setMessage(e instanceof Error ? e.message : 'No se pudo cargar el panel') } finally { setLoading(false) } }) }, [router])
  async function signOut() { await createClient().auth.signOut(); router.replace('/admin/login') }
  async function updateStock(product: Product, stock: string) { const supabase = createClient(); const token = (await supabase.auth.getSession()).data.session?.access_token; try { const updated = await api.updateProduct(product.id, { stock: Number(stock) }, token); setProducts((items) => items.map((item) => item.id === updated.id ? updated : item)); setMessage('Stock actualizado') } catch (e) { setMessage(e instanceof Error ? e.message : 'No se pudo actualizar') } }
  if (loading) return <main className="min-h-screen p-8">Cargando panel...</main>
  return <main className="min-h-screen bg-background px-4 py-6 sm:px-8"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-semibold text-primary">MAXIMA KRAFT / ADMIN</p><h1 className="font-serif text-4xl">Panel de control</h1></div><button onClick={signOut} className="rounded-full border border-border px-4 py-2 text-sm">Cerrar sesión</button></header>{message && <p className="mt-4 rounded-xl bg-muted p-3 text-sm">{message}</p>}<section className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-primary p-5 text-primary-foreground"><p className="text-sm opacity-80">Productos activos</p><strong className="text-3xl">{products.length}</strong></div><div className="rounded-2xl border border-border bg-card p-5"><p className="text-sm text-muted-foreground">Pedidos</p><strong className="text-3xl">{orders.length}</strong></div><div className="rounded-2xl border border-border bg-card p-5"><p className="text-sm text-muted-foreground">Stock bajo</p><strong className="text-3xl">{products.filter((p) => p.stock <= 5).length}</strong></div></section><section className="mt-8 rounded-2xl border border-border bg-card p-5"><h2 className="font-serif text-2xl">Inventario</h2><div className="mt-4 divide-y divide-border">{products.map((product) => <div key={product.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-medium">{product.name}</p><p className="text-sm text-muted-foreground">{product.category} · COP ${product.price.toLocaleString('es-CO')}</p></div><label className="text-sm">Stock<input aria-label={`Stock de ${product.name}`} type="number" min="0" defaultValue={product.stock} onBlur={(e) => updateStock(product, e.target.value)} className="ml-2 w-24 rounded-lg border border-input bg-background px-3 py-2" /></label></div>)}</div></section><section className="mt-8 rounded-2xl border border-border bg-card p-5"><h2 className="font-serif text-2xl">Pedidos recientes</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b border-border text-muted-foreground"><th className="p-3">Pedido</th><th className="p-3">Cliente</th><th className="p-3">Total</th><th className="p-3">Estado</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id} className="border-b border-border"><td className="p-3 font-mono">#{order.id.slice(0, 8)}</td><td className="p-3">{order.customer_name}</td><td className="p-3">COP ${Number(order.total).toLocaleString('es-CO')}</td><td className="p-3">{order.status}</td></tr>)}</tbody></table></div></section></div></main>
}
