import { Router } from 'express'
import { z } from 'zod'
import { supabase } from '../lib/supabase.js'

const router = Router()
const orderSchema = z.object({ customer_name: z.string().trim().min(2).max(120), customer_email: z.string().email().max(160), customer_phone: z.string().trim().max(30).optional(), delivery_address: z.string().trim().min(5).max(300), notes: z.string().trim().max(500).optional(), items: z.array(z.object({ product_id: z.string().uuid(), quantity: z.number().int().min(1).max(20) })).min(1).max(30) })
router.get('/', async (_req, res, next) => { try { const { data, error } = await supabase.from('orders').select('id,customer_name,customer_email,delivery_address,status,total,created_at,order_items(product_name,quantity,subtotal)').order('created_at', { ascending: false }); if (error) throw error; res.json({ data: data ?? [] }) } catch (e) { next(e) } })
router.post('/', async (req, res, next) => { try { const body = orderSchema.parse(req.body); const ids = [...new Set(body.items.map(i => i.product_id))]; const { data: products, error: productError } = await supabase.from('products').select('id,name,price,stock').in('id', ids).eq('active', true); if (productError) throw productError; if (!products || products.length !== ids.length) return res.status(400).json({ error: 'Uno o más productos no están disponibles' }); const items = body.items.map(item => { const product = products.find(p => p.id === item.product_id)!; if (item.quantity > product.stock) throw new Error(`Stock insuficiente para ${product.name}`); return { product_id: product.id, product_name: product.name, unit_price: product.price, quantity: item.quantity, subtotal: Number(product.price) * item.quantity } }); const total = items.reduce((sum, item) => sum + item.subtotal, 0); const { items: _, ...order } = body; const { data: created, error } = await supabase.from('orders').insert({ ...order, total }).select('id,customer_name,customer_email,total,status,created_at').single(); if (error) throw error; const { error: itemsError } = await supabase.from('order_items').insert(items.map(item => ({ ...item, order_id: created.id }))); if (itemsError) throw itemsError; res.status(201).json({ data: created }) } catch (e) { next(e) } })
router.patch('/:id/status', async (req, res, next) => { try { const status = z.enum(['pending','confirmed','preparing','ready','delivered','cancelled']).parse(req.body.status); const { data, error } = await supabase.from('orders').update({ status, updated_at: new Date().toISOString() }).eq('id', req.params.id).select().single(); if (error) throw error; res.json({ data }) } catch (e) { next(e) } })
export { router as ordersRouter }
